name: movie_list_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  http: ^1.1.0
  carousel_slider: ^5.0.0
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
  - assets/